server/src/component/event.rs
server/src/systems/handlers/game/mod.rs
server/src/systems/handlers/game/on_missile_fire/mod.rs
server/src/systems/handlers/game/on_missile_fire/send_player_fire.rs
server/src/systems/handlers/game/register.rs
server/src/systems/missile/fire.rs
server/src/systems/specials/config.rs
server/src/systems/specials/mod.rs
server/src/systems/specials/register.rs
server/src/systems/specials/tornado/fire.rs
server/src/systems/specials/tornado/mod.rs
server/src/types/mod.rs
server/src/types/systemdata/fire_missiles.rs
server/src/types/systemdata/mod.rs

Implements the special for tornado, uses info from issue #3. Also refactors missile firing into a custom systemdata module.

Tornado triple shot

---

CONTRIBUTORS.md
server/src/component/missile.rs
server/src/component/mod.rs
server/src/systems/missile/cull.rs
server/src/types/config.rs
server/src/types/systemdata/fire_missiles.rs

I basically don't know what I'm doing so any comments are happily appreciated. The actual distance constants in the config are wrong.

#11. Make missile lifetimes based on distance rather than time.

---

ctf/src/systems/drop_on_stealth.rs
ctf/src/systems/mod.rs
ctf/src/systems/pickupflag.rs
ctf/src/systems/register.rs

In addition to #25, also prevents prowlers from picking up the flag while stealthed.

Prowler flag bug fixes

---

notes/movement-prediction.md

Given some more time I could potentially 'clean room' this so the docs in your repo don't get polluted by actual original code, just a description of what it does. But this exists today, take it or leave it :)

Initial movement prediction notes.

---

Cargo.lock
README.md
server/src/handlers/onclose.rs
server/src/handlers/ping.rs
server/src/systems/admin/give_powerup.rs
server/src/systems/disconnect.rs
server/src/systems/handlers/game/mod.rs
server/src/systems/handlers/game/on_join/init_state.rs
server/src/systems/handlers/game/on_join/init_traits.rs
server/src/systems/handlers/game/on_join/mod.rs
server/src/systems/handlers/game/on_join/send_login.rs
server/src/systems/handlers/game/on_join/send_player_new.rs
server/src/systems/handlers/game/on_player_hit/inflict_damage.rs
server/src/systems/handlers/game/on_player_powerup/mod.rs
server/src/systems/handlers/game/on_player_powerup/register.rs
server/src/systems/handlers/game/on_player_powerup/send_player_powerup.rs
server/src/systems/handlers/game/on_player_powerup/set_powerup_lifetime.rs
server/src/systems/handlers/game/on_player_powerup/trigger_update.rs
server/src/systems/handlers/game/on_powerup_expire/force_update.rs
server/src/systems/handlers/game/register.rs
server/src/systems/position_update.rs
server/src/systems/powerups/check_expired.rs
server/src/types/powerups.rs

This PR bundles together a bunch of small bug fixes along with new systems to handle the base powerup expiry and update mechanisms.

Add powerup expiry systems

---

README.md
base/src/main.rs
server/benches/collision.rs
server/src/builder.rs
server/src/component/collision.rs
server/src/component/mod.rs
server/src/systems/collision/gen_plane_grid.rs
server/src/systems/collision/missile.rs
server/src/systems/collision/mod.rs
server/src/systems/collision/plane.rs
server/src/systems/collision/player_missile.rs
server/src/systems/collision/upgrade.rs
server/src/systems/handlers/game/on_join/send_player_powerup.rs
server/src/systems/handlers/game/on_player_powerup/mod.rs
server/src/systems/handlers/game/on_player_respawn/give_shield.rs
server/src/systems/handlers/game/on_player_respawn/mod.rs
server/src/systems/handlers/game/on_powerup_expire/mod.rs
server/src/systems/handlers/game/register.rs
server/src/systems/powerups/check_expired.rs
server/src/types/collision/grid.rs
server/tests/test-no-loops.rs

This PR bundles a bunch of small fixes that were discovered while trying to get this to work along with the changes necessary for shields.

Implement shields on spawn and on respawn

---

ctf/src/systems/flagspeed.rs
ctf/src/systems/on_flag/display_banner.rs

#72. If there is a deeper problem, this commit does not address it. But it will hopefully prevent the server from crashing.

#72. Prevent panics from calling unwrap()

---

server/src/component/time.rs
server/src/systems/handlers/command/respawn.rs
server/src/systems/handlers/command/spectate.rs

This one isn't perfect, it allows respawn during the 2 second cooldown after death, but that is a big improvement on the previous situation.. ship it!

Fix respawn logic & prevent related cheating

---

server/src/systems/handlers/command/respawn.rs
server/src/systems/handlers/command/spectate.rs

This one isn't perfect, it allows respawn during the 2 second cooldown after death, but that is a big improvement on the previous situation.. ship it!

Replace println!() in respawn code with debug!().

---

server/src/systems/admin/crash.rs
server/src/systems/admin/teleport.rs
server/src/types/config.rs

Ensure things are safe by default

Ensure admin commands respect admin_enabled, disable in release mode.

---

server/src/systems/powerups/spawn_shield.rs

Add missing setup function (like for PlaneCollisionSystem)

Fix bug with shields spawning in mountains

---

CTF.dockerfile
Dockerfile
FFA.dockerfile
README.md
ffa/src/main.rs
server/src/server/wshandler.rs
server/src/systems/handlers/command/respawn.rs
server/src/systems/handlers/game/on_player_powerup/send_player_powerup.rs

Just bringing in useful changes from the EU server implementation

Merge fixes from airmash-server-eu

---

CONTRIBUTORS.md
ctf/src/systems/register.rs

It was there in original Airmash.

Add the inferno spawn in Europe for CTF 

---

Cargo.lock
ctf/src/systems/mod.rs
ctf/src/systems/on_flag/mod.rs
ctf/src/systems/on_respawn/drop_flag.rs
ctf/src/systems/on_respawn/mod.rs
ctf/src/systems/register.rs
server/src/systems/admin/debug_print.rs
server/src/systems/admin/mod.rs
server/src/systems/admin/register.rs

See the final commit message for a more detailed write-up on how this bug worked.

Fix bug where goliaths could push other planes in to spec

---

Cargo.lock
config/stress-test.json
ctf/Cargo.toml
ctf/src/main.rs
ctf/src/tasks/new_game.rs
default-config.json
ffa/Cargo.toml
ffa/src/main.rs
server/Cargo.toml
server/src/types/config.rs

This changes config files from being a serialized representation of the Config object to only needing to specify what's been changed from the defaults.

Allow partial config files

---

ctf/src/systems/on_flag/check_win.rs
ctf/src/systems/on_flag/mod.rs
ctf/src/systems/on_flag/send_flag_message.rs
server/src/component/mod.rs
server/src/component/stats.rs
server/src/systems/mod.rs
server/src/systems/register.rs
server/src/systems/stats/frame_counter.rs
server/src/systems/stats/mod.rs
server/src/systems/stats/register.rs

Fixes the dependencies of SendFlagMessage so that it runs in the same frame as CheckWin

Fix ctf score miscount

---

server-next/src/component/mod.rs
server-next/src/consts/mod.rs
server-next/src/defaults.rs
server-next/src/event/player.rs
server-next/src/resource/game_config.rs
server-next/src/system/handler/mod.rs
server-next/src/system/handler/on_command.rs
server-next/src/system/handler/on_player_join.rs
server-next/src/system/handler/on_player_killed.rs
server-next/src/system/handler/on_player_mob_collision.rs
server-next/src/system/handler/on_player_respawn.rs
server-next/src/system/handler/on_player_spawn.rs
server-next/src/system/mod.rs
server-next/src/system/upgrades.rs
server-next/tests/behaviour/mod.rs
server-next/tests/behaviour/upgrades.rs

This option is present in the other server and people seem to like it so it's worth carrying over to here.

Add option to always have players at 5555 upgrades

---

ctf/src/config.rs
ctf/src/systems/mod.rs
ffa/src/systems.rs
server-macros/src/handler.rs
server-next/src/consts/hitcircles.rs
server-next/src/dispatch.rs
server-next/src/mock.rs
server-next/src/network.rs
server-next/src/resource/collision.rs
server-next/src/system/handler/chat.rs
server-next/src/system/handler/on_command.rs
server-next/src/system/handler/on_event_horizon.rs
server-next/src/system/handler/on_player_fire.rs
server-next/src/system/handler/on_player_killed.rs
server-next/src/system/handler/on_player_leave.rs
server-next/src/system/handler/on_player_mob_collision.rs
server-next/src/system/handler/on_player_powerup.rs
server-next/src/system/handler/on_player_repel.rs
server-next/src/system/network.rs
server-next/src/system/physics.rs
server-next/src/system/scoreboard.rs
server-next/src/system/specials.rs
server-next/src/task.rs
utils/kdtree/src/aabb.rs
utils/kdtree/src/kdtree.rs
utils/special-map/src/lib.rs

As in title. Most have been fixed - a few have been ignored where I found that the suggestion made things less clear.

Fix or ignore all warnings emitted by clippy

---

.github/workflows/auto-dependabot.yml

Add workflow to automatically merge dependabot PRs if they pass CI

---

configs/lazormissiles.json

As in the title - is somewhat fun to play with.

Add a config with extra-fast missiles

---

Cargo.lock
Cargo.toml
server-config/Cargo.toml
server-config/configs/default.lua
server-config/configs/infinite-fire.lua
server-config/examples/export.rs
server-config/examples/validate.rs
server-config/src/common.rs
server-config/src/config.rs
server-config/src/error.rs
server-config/src/game.rs
server-config/src/lib.rs
server-config/src/missile.rs
server-config/src/plane.rs
server-config/src/script.rs
server-config/src/special.rs
server-config/src/util.rs

This PR introduces the first set of prototypes along with a LUA scripting mechanism to apply changes to them.

Introduce a separate `server-config` crate for server configs

---

configs/default.json
configs/hyperspeed.json
configs/infinite-fire.json
ctf/tests/game-score-reset.rs
server/src/resource/config.rs
server/src/resource/game_config.rs
server/src/system/admin.rs
server/tests/behaviour/admin.rs

This is a redo of #208 that also makes sure that the configs are updated appropriately.

Delete the `Config:admin_enabled` field in favour of `GameConfig::admin_enabled`

---

server-config/src/config.rs
server-config/src/effect.rs
server-config/src/game.rs
server-config/src/lib.rs
server-config/src/missile.rs
server-config/src/mob.rs
server-config/src/plane.rs
server-config/src/special.rs
server-config/src/util.rs

This currently has all the effects I could think of that are used in the base airmash game.

Implement an effect prototype within `server-config`

---

Cargo.lock
Cargo.toml
server/Cargo.toml
server/src/world.rs
utils/anymap/Cargo.toml
utils/anymap/build.rs
utils/anymap/src/dbg.rs
utils/anymap/src/lib.rs

Anymap has been unmaintained for years. This PR replaces it with a more minimal version that also supports some useful extras such a debugging the map on nightly.

Replace anymap with a local version

---

server/src/mock.rs

More and more test cases are going to need to modify the config - they should be using the new config and this constructor makes it easy.

Add a with_config constructor to TestGame

---

utils/serde-rlua/src/de.rs

The problem is that for lua tables there is no difference between a key that doesn't exist and one that corresponds to nil (in fact assigning nil is how you remove a key from the table). However, we serialize options to nil when they are None so we can run into this with structs pretty easily.
The solution here is to track the extra fields in the struct and explicitly deserialize a nil as their value if they are not found within the table that is being deserialized. This ensures that all the downstream structs in server-config deserialize properly.
We will still have some issues around maps that contain options but that's a much rarer case than structs with options so I'm ok with that for now.

Ensure that structs with options deserialize properly
