protocol-common/src/enums/command_reply_type.rs
protocol-common/src/enums/powerup_type.rs
protocol-common/src/packets/client/command.rs
protocol-v5/src/error.rs
protocol-v5/src/funcs/low_res_pos.rs
protocol-v5/src/lib.rs
server/src/component/channel.rs
server/src/component/event.rs
server/src/lib.rs
server/src/systems/admin/give_powerup.rs
server/src/systems/admin/mod.rs
server/src/systems/handlers/game/mod.rs
server/src/systems/handlers/game/on_join/mod.rs
server/src/systems/handlers/game/on_join/send_login.rs
server/src/systems/handlers/game/on_join/send_player_new.rs
server/src/systems/handlers/game/on_join/send_player_powerup.rs
server/src/systems/handlers/game/on_player_hit/inflict_damage.rs
server/src/systems/handlers/game/on_powerup_expire/force_update.rs
server/src/systems/handlers/game/on_powerup_expire/mod.rs
server/src/systems/handlers/game/register.rs
server/src/systems/mod.rs
server/src/systems/position_update.rs
server/src/systems/powerups/check_expired.rs
server/src/systems/powerups/mod.rs
server/src/systems/powerups/register.rs
server/src/systems/register.rs
server/src/types/config.rs
server/src/types/powerups.rs
server/src/utils/event_handler.rs

This adds support to the engine for shields. It will give joining players shields and adds a command to give a shield to any player, but it doesn't add any code for spawning shield powerups anywhere. It also doesn't add support for respawning players to have shields.
One other note: This bundles a fix for a serialization error in minimap lowres positions.

Implement support for shield powerup

---

server/src/systems/handlers/game/on_player_hit/mod.rs
server/src/systems/handlers/game/on_player_killed/display_message.rs
server/src/systems/handlers/game/on_player_killed/set_respawn_timer.rs

The bug was causd by the player killed event queue message being
scheduled between the system that sent out the ScoreUpdate packet
and the system that sent out the PlayerKilled packet.

Fix dependencies of player killed handlers (fixes #20)

---

ctf/src/systems/on_flag/mod.rs
ctf/src/systems/on_flag/send_flag_message.rs
ctf/src/systems/on_game_win/mod.rs
ctf/src/systems/on_game_win/reset_flags.rs
ctf/src/systems/register.rs
protocol-common/src/enums/flag_update_type.rs
server/src/lib.rs

This pr fixes the following bugs:
- Players can hold onto flags into the intermission (roughly #28)
- Flag teleports to the origin when the other team caps if a player is carrying (issue #21)

Fix game flag handling bugs

---

server/src/handlers/command.rs

Players can still immediately respawn after reaching full health, i.e. #24 still does not work. Also, I was under the impression that you needed full health before respawning, and not 90-95%.

#23. Make sure players have full health before allowing respawn

---

ctf/src/systems/drop_on_respawn.rs
ctf/src/systems/mod.rs
ctf/src/systems/register.rs

More or less a shameless copy of `drop_on_spec.rs`, but it works! That code contains this piece of code which I'm not totally sure what it does, but removing it is necessary for the code to work with respawning instead of spec.
```rust
let target: i32 = match packet.data.parse() {
Ok(v) => v,
Err(_) => continue,
};
match target {
-3...-1 => (),
_ => continue,
}
```

#27: Drop flag on respawn

---

server/src/types/config.rs

Method: paste this into the console and fire a bunch of missiles. `mobDestroyed` overestimates distances, so `mobDespawned` is used instead.
```js
let missilePositions = {}
let distances = {}
let dist = (x1, y1, x2, y2) => Math.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2);
let average = (arr) => arr.reduce((a, b) => a + b, 0) / arr.length;
SWAM.on("mobAdded", function (missile) {
missilePositions[missile.id] = [missile.posX, missile.posY]
});
SWAM.on("mobDespawned", function (mob) {
let missile = Mobs.get(mob.id);
let [posX, posY] = missilePositions[missile.id]
distances[missile.type] = distances[missile.type] || [];
if (missile.pos) {
distances[missile.type].push(dist(posX, posY, missile.pos.x, missile.pos.y))
console.log(`Average for missile type ${missile.type}: …
```

Fix #16: Determine missile ranges for all planes

---

protocol-common/src/packets/server/player_powerup.rs
server/src/systems/handlers/game/on_join/send_player_powerup.rs

The issue was caused by sending `PlayerPowerup` to all players. This fixes that and changes the documentation for `PlayerPowerup` to clarify that it applies to the player that receives it.

Fix Issue #30 spawn shield incorrect

---

server/src/handlers/key.rs
server/src/systems/handlers/command/respawn.rs
server/src/systems/handlers/command/spectate.rs
server/src/systems/handlers/game/on_join/init_traits.rs

This rewrites the logic in the respawn and spectate handlers to deal with respawning after 2s and to have the health logic.

Fix issue #24 and issue #40

---

Cargo.lock
server/Cargo.toml
server/src/handlers/onopen.rs
server/src/lib.rs
server/src/server.rs
server/src/systems/packet_handler.rs
server/src/systems/poll_complete.rs
server/src/types/connection.rs
server/src/types/connection_events.rs
server/src/types/mod.rs

[websocket](https://github.com/websockets-rs/rust-websocket) no longer appears to be maintained. Switching to [ws-rs](https://github.com/housleyjk/ws-rs) allows for several dependencies to be updated.

Switch websocket library to ws-rs

---

server/src/types/components.rs

expr was being parsed as (secs*1e6) + (usecs/10)
expr should produce duration measured in hundreds of a millisecond, so:
((secs*1e6)+usecs)/10
See js/Network.js dispatchIncomingMessage - value is divided by 100 then
compared against performance.now(), which is measured in milliseconds.

Fix #89 - jitter due to to_clock() operator precedence bug

---

ffa/src/main.rs
server/src/systems/collision/missile.rs
server/src/systems/collision/plane.rs

Per previous conversations, Rayon is extremely aggressive and has perhaps a worst-case busywaiting behaviour given the Airmash workload. On a 16 thread machine it's possible to observe it consuming 8 full cores, doing nothing more than calling `sched_yield()` in a loop, with most of the CPU time being burned in the kernel scheduler.
These changes help bring the server down to something more reasonable - 10% of one core given around 30 connections.

Rayon taming & blast radius reduction

---

.circleci/config.yml

rustfmt is currently broken in nightly so instead we'll just disable the formatting check as it wasn't hugely useful anyway.

Disable formatting check in CI

---

server/src/systems/handlers/game/on_player_powerup/set_powerup_lifetime.rs

Addresses the newest crash in #85

Fix crash when a player picks up a powerup then immediately leaves

---

server/src/systems/handlers/game/on_player_powerup/trigger_update.rs

Fix a crash similar to f315fcd14ca6c6940ebe286cf1b813b19be69418
<details><summary>Backtrace:</summary>
<p>
```
**thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WrongGeneration(WrongGeneration { action: "insert component for entity", actual_gen: Generation(-15), entity: Entity(41
0, Generation(15)) })', src/libcore/result.rs:1084:5
stack backtrace:
0: backtrace::backtrace::libunwind::trace
at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
1: backtrace::backtrace::trace_unsynchronized
at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
2: std::sys_common::backtrace::_print
at src/libstd/sys_common/backtrace.rs:47
3: std::sys_common::backtrace::print
at …
```

Fix another crash (#85)

---

config/default.json
config/no-moving-spectate.json
ffa/src/main.rs
server/src/bin/dump-config.rs
server/src/systems/handlers/command/spectate.rs
server/src/types/config.rs

In addition, disable going into spectate while moving by default for FFA

Add config option to disallow going into spec while moving

---

Cargo.lock
ctf/src/main.rs
server/src/bin/dump-config.rs
server/src/systems/handlers/command/spectate.rs
server/src/systems/handlers/game/on_player_respawn/send_player_respawn.rs
server/src/task/death_cooldown.rs
server/src/types/connection.rs
server/src/types/systemdata/send_to_visible.rs

Root cause turned out that respawn packets were not sent to a player when they respawn far away from spawn. This mainly happened in CTF since in FFA players tend to remain close to their respawn points.

Fix missing health and energy indicators

---

Cargo.lock
server-next/Cargo.toml
server-next/src/network.rs
server-next/src/util/escapes.rs
server-next/src/util/mod.rs

Due to some changes in tungstenite or tokio-tungstenite it is no longer possible to return a response from accept_hdr_async that is not either
1. the continuation of the websocket handshake, or
2. an error response.
This causes a problem for airmash servers since the client actually queries the server endpoint and expects a 200 OK response with a json payload if the request is not a websocket request. To work around this, I have manually reimplemented the websocket handshake so that we can return the expected results when a non-websocket request comes in.

Fix status page to actually return the number of players

---

server-next/src/system/handler/on_player_join.rs

Previously, when a player joined their score would be blank until they got a kill or otherwise had their score updated. This commit fixes that so that they are assigned an initial score.

Send initial ScoreUpdate packet when a player joins

---

server-next/src/network.rs

Turns out that requests aren't made to the root path all the time. This switches up the network handshake to respond to all request paths.

Allow any request path to the server

---

base/src/main.rs

Previously, airmash-server-base would forcibly override the RUST_BACKTRACE and RUST_LOG environment variables. We'd like to actually be able to configure those so this PR changes airmash-server-base to only set them if they are not already present in the environment.

Prevent airmash-server-base from overriding RUST_LOG and RUST_BACKTRACE

---

server-next/src/component/mod.rs
server-next/src/defaults.rs
server-next/src/event/packet.rs
server-next/src/mock.rs
server-next/src/network.rs
server-next/src/system/ctf.rs
server-next/src/system/ffa.rs
server-next/src/system/network.rs
server-next/src/system/ping.rs
server-next/src/util/mod.rs

Previously, the estimated ping times by the server were fixed to multiples of the server frame time (16ms). This is obviously wrong so this PR is a set of changes to make it return something closer to the real ping time.

Make server-estimated ping times more accurate

---

.github/workflows/build-project.yml

This ensures that the debug and release jobs don't share caches. This avoids one of them having to rebuild everything every time.

Use build config in CI cache key

---

Cargo.lock
server-next/Cargo.toml

As a bonus, this also allows for using an updated version of nalgebra.

Update airmash-protocol to use the version on crates.io

---

server-next/src/component/mod.rs
server-next/src/system/handler/on_player_mob_collision.rs
server-next/tests/behaviour/mod.rs
server-next/tests/behaviour/powerups.rs

Currently, if a powerup is spawned and a player goes to pick it up then the powerup will despawn but the player will not be given the corresponding effect. This PR changes that to now give the player the expected effect. I've also included tests to verify that everything works as expected.

Make picking up a powerup grant the corresponding effect

---

ctf/src/config.rs

The updated client at https://airmash.online now performs HTML escaping for any message not matching a very specific template so in order for the message to be shown properly we need to match that template.

Change span class used in flag messages to (blue|red)flag

---

Cargo.lock
configs/default.json
server-next/Cargo.toml
server-next/examples/export-config.rs
server-next/src/component/mod.rs
server-next/src/defaults.rs
server-next/src/resource/config.rs
server-next/src/system/keys.rs
server-next/tests/behaviour/visibility.rs

Currently, all missiles from all planes are fired from the centre of the plane. However, this is not correct for the mohawk which is supposed to fire with the offset switching sides with each shot. This PR adds this behaviour. Note that this involves a change to the config so I've added a small utility to export the default config and then gone and updated it.

Make mohawk missiles fire on alternating sides of the plane

---

configs/default.json
configs/infinite-fire.json
configs/stress-test.json
server-next/Cargo.toml
server-next/src/resource/config.rs

As in title. This required some pretty big changes to `serde-deserialize-over` but now that those have been made we can make the config easier to write and understand.

Change the serialized form of durations to be a float

---

Cargo.lock
server-next/Cargo.toml
server-next/src/world.rs

Anymap 0.12.1 is insecure but there's no non-beta updated version so instead we'll be using the beta version for now

Bump anymap from 0.12.1 to 1.0.0-beta.2

---

Cargo.lock
server-next/Cargo.toml

These need to be updated in lockstep since they are exposed as part of airmash-protocol's API

Update both nalgebra and airmash-protocol

---

server-next/src/component/mod.rs
server-next/src/system/keys.rs
server-next/src/system/specials.rs
server-next/src/worldext.rs

I'd like to support modes where the game is more easily modifiable through config files. This PR is one part of this whole effort. At the moment it doesn't add new capabilities but it does make experimenting with missile multi-shot from planes much easier.
Note that it's not yet used for the tornado special since the current config setup has the offsets for missiles associated with the plane and not the missile type.

Add support for firing arbitrary numbers of missiles from planes

---

.github/workflows/auto-dependabot.yml

pull_request_target workflows are not given access to any dependabot secrets at all so they will not work.

Convert dependabot automerge workflow to use pull_request

---

Cargo.lock
Cargo.toml
utils/serde-rlua/Cargo.toml
utils/serde-rlua/src/de.rs
utils/serde-rlua/src/error.rs
utils/serde-rlua/src/lib.rs
utils/serde-rlua/src/ser.rs

This is mostly a carbon-copy of the source code of the `rlua_serde` crate but updated to work with the most recent version of `rlua` and have better error messages when deserialization doesn't work.
None of this code is used just yet, but it will be used by future work in the config system.

Introduce a crate to serialize/deserialize from rlua Values

---

server-config/src/common.rs
server-config/src/config.rs
server-config/src/game.rs
server-config/src/lib.rs
server-config/src/missile.rs
server-config/src/plane.rs
server-config/src/script.rs
server-config/src/special.rs

This commit is a rather big design change in how prototypes are written and used. Before this, references to other prototypes were just strings. If you wanted to get the prototype that it was referring to it was necessary to go and look it up in the hashmaps contained within GameConfig. This was doable, if inconvenient.
It would be much more convenient if, instead of going through strings and hashmaps, we could just directly access the corresponding prototype to do this. This commit makes it so this approach works.
The way it does this is like so:
- Prototypes are parameterized by a type implementing the trait PrototypeRef. This is a sealed trait which provides a few associated types which are the types of each individual prototype reference.
- There are two concrete implementors of …

Allow prototype references to be actual references

---

server-config/src/special.rs

Having to match on the data enum every time we want to get a specific
type is verbose. Using accessors and options is more convenient.

Add accessors to SpecialPrototype

---

server-config/src/config.rs
server-config/src/game.rs
server-config/src/lib.rs
server-config/src/mob.rs
server/src/lib.rs
server/src/resource/config.rs
server/src/system/handler/on_event_boost.rs
server/src/system/handler/on_event_horizon.rs
server/src/system/handler/on_missile_despawn.rs
server/src/system/handler/on_missile_terrain_collision.rs
server/src/system/handler/on_mob_spawn.rs
server/src/system/handler/on_player_fire.rs
server/src/system/handler/on_player_killed.rs
server/src/system/handler/on_player_missile_collision.rs
server/src/system/handler/on_player_mob_collision.rs
server/src/system/handler/on_player_repel.rs
server/src/system/physics.rs
server/src/worldext.rs
server/tests/behaviour/prowler.rs

This means that we can deprecated the most used fields of `Config` in preparation for replacing them with the structs defined in `server-config`.

Replace most uses of `MobType` with mob or missile prototypes

---

server/src/system/handler/on_command.rs
server/tests/behaviour/respawn.rs

Fixes #201. See that issue for a description of the root cause. This PR adds a fix as well as a test case to ensure it doesn't happen again.

Sequence `PLAYER_TYPE` messages before `PLAYER_RESPAWN` messages for plane change commands

---

ctf/tests/game-score-reset.rs
server/src/resource/config.rs
server/src/resource/game_config.rs
server/src/system/admin.rs
server/tests/behaviour/admin.rs

As in the title, this is the first step in replacing `Config` with `server_config::GameConfig` everywhere.

Delete the `Config:admin_enabled` field in favour of `GameConfig::admin_enabled`

---

ctf/tests/game-score-reset.rs
server/src/resource/config.rs
server/src/resource/game_config.rs
server/src/system/admin.rs
server/tests/behaviour/admin.rs

Reverts steamroller-airmash/airmash-server#208

Revert "Delete the `Config:admin_enabled` field in favour of `GameConfig::admin_enabled`"

---

server-config/src/config.rs
server-config/src/error.rs
server-config/src/lib.rs
server-config/src/util.rs

This needed a bit of unsafe code and a couple of helpers but we're already using some unsafe code in that area so the extra bit isn't that bad.

Eliminate memory leaks within `GameConfig::new`

---

server-config/src/config.rs
server-config/src/effect.rs
server-config/src/game.rs
server-config/src/lib.rs
server-config/src/mob.rs
server-config/src/plane.rs
server-config/src/powerup.rs
server-config/src/special.rs
server/src/component/effect.rs
server/src/component/mod.rs
server/src/defaults.rs
server/src/event/player.rs
server/src/lib.rs
server/src/system/handler/on_player_join.rs
server/src/system/handler/on_player_missile_collision.rs
server/src/system/handler/on_player_mob_collision.rs
server/src/system/handler/on_player_powerup.rs
server/src/system/handler/on_player_respawn.rs
server/src/system/keys.rs
server/src/system/physics.rs
server/src/system/powerups.rs
server/src/system/specials.rs
server/src/util/mod.rs
server/tests/behaviour/powerups.rs

This doesn't quite fully leverage the power of the effects system yet but it's enough to duplicate the previous functionality.

Swap all existing powerup code over to using the effects system

---

Cargo.lock
server/Cargo.toml
server/src/system/handler/on_command.rs

As in title. Also supports an `/uptime raw` variant that just gives the raw time in seconds for use by scripts and bots.

Add a /uptime command to get server uptime

---

Cargo.lock
utils/anymap/Cargo.toml

Dependabot's security alerts don't seem smart enough to figure out that we're using a local version of anymap so this will bump the version to something that doesn't trigger the security alert.

Bump anymap version to 1.0.0

---

configs/default.json
configs/no-moving-spectate.json
ctf/src/main.rs
ffa/src/main.rs
server/src/resource/config.rs

The `allow_spectate_while_moving` config option is unused so there's no point in keeping it around at the moment since it doesn't do what it's advertised to do anyway.

Remove unused flag

---

Cargo.lock
base/Cargo.toml
base/src/main.rs
ctf/Cargo.toml
ffa/Cargo.toml
ffa/src/main.rs
ffa/src/systems.rs
server-macros/src/handler.rs
server-macros/src/lib.rs
server/Cargo.toml
server/src/event/mod.rs
server/src/lib.rs
server/src/macros.rs
server/tests/all_tests.rs
server/tests/behaviour/admin.rs
server/tests/behaviour/despawn.rs
server/tests/behaviour/powerups.rs
server/tests/behaviour/prowler.rs
server/tests/behaviour/respawn.rs
server/tests/behaviour/shoot.rs
server/tests/behaviour/upgrades.rs
server/tests/behaviour/visibility.rs
server/tests/task.rs
server/tests/utils/mod.rs

It was referred to by 3 different names across each of the crates. This PR changes things to refer to it as `airmash` everywhere.

Standardize naming of the server crate

---

server/src/system/handler/on_player_respawn.rs
server/src/system/handler/on_player_spawn.rs
server/tests/behaviour/powerups.rs

The problem was that spawn shields were only given as part of the `PlayerRespawn` event which isn't triggered when a player joins. Instead, this moves that to `PlayerSpawn` which is also fired when a player joins.
Fixes #215

Ensure that players are given a spawn shield when they initially join
